version: '3'
services:
  inv-db:
    image: postgres
    container_name: inv-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    networks:
      - app-network

  inv-app:
    image: investment-app
    container_name: inv-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - inv-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge