create table users (
    id int8 generated by default as identity,
    login varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);

create table roles (
   role varchar(255),
   primary key (role)
);

create table brokerage_accounts (
    id int8 generated by default as identity,
    name varchar(255) not null,
    user_id int8 not null,
    primary key (id)
);

create table brokerage_account_securities (
    id int8 generated by default as identity,
    count int8 not null,
    ticker varchar(255) not null unique,
    brokerage_account_id int8 not null,
    primary key (id)
);

alter table users
add constraint users_role_fk
foreign key (role) references roles;

alter table brokerage_accounts
add constraint brokerage_accounts_users_fk
foreign key (user_id) references users;

alter table brokerage_account_securities
add constraint brokerage_account_securities_brokerage_accounts_fk
foreign key (brokerage_account_id) references brokerage_accounts;

