create table brokerage_account_securities_history (
    id int8 generated by default as identity,
    date TIMESTAMP NOT NULL,
    brokerage_account_id int8,
    ticker varchar(128) NOT NULL,
    price real NOT NULL,
    primary key (id),
    foreign key (brokerage_account_id) references brokerage_account_securities(id)
);